// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voting/protobuf/voting/ballot.proto

package voting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ballot represents a ballot casted by an user
type Ballot struct {
	VoteId               string   `protobuf:"bytes,1,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	HashedCode           string   `protobuf:"bytes,2,opt,name=hashed_code,json=hashedCode,proto3" json:"hashed_code,omitempty"`
	Choice               string   `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	CastedAt             int64    `protobuf:"varint,14,opt,name=casted_at,json=castedAt,proto3" json:"casted_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ballot) Reset()         { *m = Ballot{} }
func (m *Ballot) String() string { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()    {}
func (*Ballot) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d7f1fa6785691c, []int{0}
}

func (m *Ballot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ballot.Unmarshal(m, b)
}
func (m *Ballot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ballot.Marshal(b, m, deterministic)
}
func (m *Ballot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ballot.Merge(m, src)
}
func (m *Ballot) XXX_Size() int {
	return xxx_messageInfo_Ballot.Size(m)
}
func (m *Ballot) XXX_DiscardUnknown() {
	xxx_messageInfo_Ballot.DiscardUnknown(m)
}

var xxx_messageInfo_Ballot proto.InternalMessageInfo

func (m *Ballot) GetVoteId() string {
	if m != nil {
		return m.VoteId
	}
	return ""
}

func (m *Ballot) GetHashedCode() string {
	if m != nil {
		return m.HashedCode
	}
	return ""
}

func (m *Ballot) GetChoice() string {
	if m != nil {
		return m.Choice
	}
	return ""
}

func (m *Ballot) GetCastedAt() int64 {
	if m != nil {
		return m.CastedAt
	}
	return 0
}

func (m *Ballot) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Ballot)(nil), "voting.Ballot")
}

func init() {
	proto.RegisterFile("voting/protobuf/voting/ballot.proto", fileDescriptor_75d7f1fa6785691c)
}

var fileDescriptor_75d7f1fa6785691c = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0x62, 0x21, 0xda, 0x13, 0x14, 0x32, 0x68, 0x40, 0xc4, 0xa2, 0x4b, 0x27, 0x3b,
	0xf8, 0x04, 0xd5, 0xc9, 0xb5, 0x2f, 0x50, 0xd2, 0xe4, 0xb4, 0x85, 0xe2, 0x49, 0x7b, 0xf6, 0x51,
	0x7c, 0x5e, 0x31, 0xc9, 0xf8, 0xfd, 0xfe, 0x09, 0x1c, 0x9c, 0x26, 0xe2, 0xee, 0xf5, 0x2c, 0xde,
	0x03, 0x31, 0x35, 0x9f, 0x47, 0x11, 0x77, 0x63, 0xfa, 0x9e, 0xf8, 0xec, 0x59, 0xc9, 0x80, 0xc7,
	0xaf, 0x00, 0x79, 0xf5, 0x41, 0x6d, 0x61, 0x3e, 0x11, 0x63, 0xdd, 0x39, 0x2d, 0x32, 0x91, 0xa7,
	0xd5, 0xff, 0x0d, 0xde, 0x9d, 0x3a, 0xc0, 0xb2, 0x35, 0x63, 0x8b, 0xae, 0xb6, 0xe4, 0x50, 0xcf,
	0x7c, 0x84, 0x40, 0x37, 0x72, 0xa8, 0x36, 0x20, 0x6d, 0x4b, 0x9d, 0x45, 0x9d, 0x84, 0x8f, 0x61,
	0xa9, 0x1d, 0xa4, 0xd6, 0x8c, 0x8c, 0xae, 0x36, 0xac, 0x57, 0x99, 0xc8, 0x93, 0x6a, 0x11, 0xa0,
	0x64, 0xb5, 0x07, 0xb0, 0x03, 0x9a, 0x58, 0xd7, 0xbe, 0xa6, 0x51, 0x4a, 0x6e, 0xa4, 0xbf, 0xf3,
	0xf2, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x69, 0x9f, 0x71, 0xe9, 0xce, 0x00, 0x00, 0x00,
}
