// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voting/protobuf/voting/ballot.proto

package voting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ballot_State int32

const (
	Ballot_NOT_IN_RESULT    Ballot_State = 0
	Ballot_IN_RESULT_TOTAL  Ballot_State = 1
	Ballot_IN_RESULT_CASTED Ballot_State = 2
)

var Ballot_State_name = map[int32]string{
	0: "NOT_IN_RESULT",
	1: "IN_RESULT_TOTAL",
	2: "IN_RESULT_CASTED",
}

var Ballot_State_value = map[string]int32{
	"NOT_IN_RESULT":    0,
	"IN_RESULT_TOTAL":  1,
	"IN_RESULT_CASTED": 2,
}

func (x Ballot_State) String() string {
	return proto.EnumName(Ballot_State_name, int32(x))
}

func (Ballot_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75d7f1fa6785691c, []int{0, 0}
}

// Ballot represents a ballot casted by an user
type Ballot struct {
	VoteId               string       `protobuf:"bytes,1,opt,name=vote_id,json=voteId,proto3" json:"vote_id,omitempty"`
	HashedCode           string       `protobuf:"bytes,2,opt,name=hashed_code,json=hashedCode,proto3" json:"hashed_code,omitempty"`
	Choice               string       `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	State                Ballot_State `protobuf:"varint,4,opt,name=state,proto3,enum=voting.Ballot_State" json:"state,omitempty"`
	CastedAt             int64        `protobuf:"varint,5,opt,name=casted_at,json=castedAt,proto3" json:"casted_at,omitempty"`
	CreatedAt            int64        `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Ballot) Reset()         { *m = Ballot{} }
func (m *Ballot) String() string { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()    {}
func (*Ballot) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d7f1fa6785691c, []int{0}
}

func (m *Ballot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ballot.Unmarshal(m, b)
}
func (m *Ballot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ballot.Marshal(b, m, deterministic)
}
func (m *Ballot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ballot.Merge(m, src)
}
func (m *Ballot) XXX_Size() int {
	return xxx_messageInfo_Ballot.Size(m)
}
func (m *Ballot) XXX_DiscardUnknown() {
	xxx_messageInfo_Ballot.DiscardUnknown(m)
}

var xxx_messageInfo_Ballot proto.InternalMessageInfo

func (m *Ballot) GetVoteId() string {
	if m != nil {
		return m.VoteId
	}
	return ""
}

func (m *Ballot) GetHashedCode() string {
	if m != nil {
		return m.HashedCode
	}
	return ""
}

func (m *Ballot) GetChoice() string {
	if m != nil {
		return m.Choice
	}
	return ""
}

func (m *Ballot) GetState() Ballot_State {
	if m != nil {
		return m.State
	}
	return Ballot_NOT_IN_RESULT
}

func (m *Ballot) GetCastedAt() int64 {
	if m != nil {
		return m.CastedAt
	}
	return 0
}

func (m *Ballot) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("voting.Ballot_State", Ballot_State_name, Ballot_State_value)
	proto.RegisterType((*Ballot)(nil), "voting.Ballot")
}

func init() {
	proto.RegisterFile("voting/protobuf/voting/ballot.proto", fileDescriptor_75d7f1fa6785691c)
}

var fileDescriptor_75d7f1fa6785691c = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xed, 0x66, 0xab, 0x3d, 0xa2, 0xab, 0xc7, 0xa1, 0x01, 0x11, 0xcb, 0xbc, 0x29, 0x5e,
	0x74, 0xa0, 0x4f, 0x50, 0x67, 0x2f, 0x06, 0x63, 0x83, 0x36, 0x5e, 0x87, 0x34, 0x89, 0xb6, 0x30,
	0x8c, 0xac, 0xc7, 0xbd, 0x83, 0x6f, 0x2d, 0x4b, 0x8a, 0x5e, 0xfe, 0xdf, 0xf7, 0x27, 0x3f, 0x1c,
	0x78, 0xd8, 0x5b, 0xea, 0x3e, 0x3f, 0xe6, 0x5f, 0x3b, 0x4b, 0xb6, 0xf9, 0x7e, 0x9f, 0x0f, 0xb9,
	0x91, 0xdb, 0xad, 0xa5, 0xdc, 0x61, 0x8c, 0x3c, 0x9c, 0xfd, 0x8c, 0x20, 0x7a, 0x71, 0x02, 0x6f,
	0xe0, 0x64, 0x6f, 0xc9, 0x88, 0x4e, 0xb3, 0x20, 0x0d, 0xb2, 0xb8, 0x3a, 0x74, 0xcc, 0x52, 0xe3,
	0x3d, 0x9c, 0xb5, 0xb2, 0x6f, 0x8d, 0x16, 0xca, 0x6a, 0xc3, 0x46, 0x4e, 0x82, 0x47, 0x0b, 0xab,
	0x0d, 0x5e, 0x43, 0xa4, 0x5a, 0xdb, 0x29, 0xc3, 0xc6, 0xfe, 0xa1, 0x4f, 0xf8, 0x08, 0x61, 0x4f,
	0x92, 0x0c, 0x3b, 0x4e, 0x83, 0xec, 0xe2, 0x69, 0x9a, 0xfb, 0xd1, 0xdc, 0x0f, 0xe6, 0xf5, 0xc1,
	0x55, 0xbe, 0x82, 0xb7, 0x10, 0x2b, 0xd9, 0x93, 0xd1, 0x42, 0x12, 0x0b, 0xd3, 0x20, 0x1b, 0x57,
	0xa7, 0x1e, 0x14, 0x84, 0x77, 0x00, 0x6a, 0x67, 0xe4, 0x60, 0x27, 0xce, 0xc6, 0x03, 0x29, 0x68,
	0x56, 0x42, 0xe8, 0xfe, 0xc2, 0x4b, 0x38, 0x5f, 0x6f, 0xb8, 0x58, 0xae, 0x45, 0x55, 0xd6, 0x6f,
	0x2b, 0x9e, 0x1c, 0xe1, 0x15, 0x4c, 0xfe, 0xa2, 0xe0, 0x1b, 0x5e, 0xac, 0x92, 0x00, 0xa7, 0x90,
	0xfc, 0xc3, 0x45, 0x51, 0xf3, 0xf2, 0x35, 0x19, 0x35, 0x91, 0x3b, 0xcd, 0xf3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0x7b, 0xa3, 0x0f, 0x41, 0x01, 0x00, 0x00,
}
